#include <genesis.h>

#ifndef MAP_RESTRICTION_
#define MAP_RESTRICTION_

// HAY QUE AJUSTAR ESTE NUMERO
#define MAP_RESTRICTION_COUNT 65

// 0bTTTTDDDD
// T = Tipo
// D = Direccion

const u16 map_restrictions[MAP_RESTRICTION_COUNT] = {
0,//Hueco
// 1
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN,
MAP_RESTRICTION_DOWN,

// 2
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_UP,
MAP_RESTRICTION_UP,

// 3

MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISBOTTOMTILE | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_UP,
MAP_RESTRICTION_UP,

// 4
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_RIGHT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_LEFT,

// 5
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
MAP_RESTRICTION_RIGHT,
MAP_RESTRICTION_LEFT,

// 6
MAP_RESTRICTION_DOWN,
MAP_RESTRICTION_DOWN,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
};

#endif

