#include <genesis.h>

#ifndef MAP_RESTRICTION_
#define MAP_RESTRICTION_

#define MAP_RESTRICTION_COUNT 72

// 0bTTTTDDDD
// T = Tipo
// D = Direccion

const u16 map_restrictions[MAP_RESTRICTION_COUNT] = {
0,//Hueco
//Suelo
MAP_RESTRICTION_DOWN,
//Cuesta1
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1b
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPDISPLACED | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta2
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1 Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1b Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPDISPLACED | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta2 Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD | MAP_RESTRICTION_ISBOTTOMTILE,
//Bordes LR
0,
0,
//Plataforma
MAP_RESTRICTION_DOWN,
//Bordebajo
0,
//Cuesta1
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1b
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPDISPLACED | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta2
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPHARD | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1 Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta1b Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPDISPLACED,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPDISPLACED | MAP_RESTRICTION_ISBOTTOMTILE,
//Cuesta2 Left
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_ISRAMP | MAP_RESTRICTION_ISRAMPLEFT | MAP_RESTRICTION_ISRAMPHARD | MAP_RESTRICTION_ISBOTTOMTILE,
//Bordes LR
0,
0,
//
0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
//
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_RIGHT,
MAP_RESTRICTION_RIGHT,
0,
MAP_RESTRICTION_DOWN | MAP_RESTRICTION_LEFT,
MAP_RESTRICTION_LEFT,
0
};

#endif

